-- Create a queue table for WA bot notifications
create table if not exists public.bot_queue (
  id bigint generated by default as identity primary key,
  payload jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS but restrict all direct web access
alter table public.bot_queue enable row level security;

-- Only service role (Vercel API & Bot API) can access this table, bypassing RLS
